production:
  adapter: mysql2
  database: waker
  encoding: utf8mb4
  username : <%= ENV['MYSQL_USER'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>

development:
  adapter: mysql2
  database: waker_development
  encoding: utf8mb4
  username : <%= ENV['MYSQL_USER'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>

test:
  adapter: mysql2
  database: waker_test
  encoding: utf8mb4
  username : <%= ENV['MYSQL_USER'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>
