development:
  adapter: mysql2
  database: waker_development
  encoding: utf8mb4
  username: root
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>

test:
  adapter: mysql2
  database: waker_test
  encoding: utf8mb4
  username: root
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>
